version: '3.9'

services:
  contacorrente-api:
    build:
      context: .
      dockerfile: src/ContaCorrente.Api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/database
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/database/contacorrente.db